/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Job {
    id: bigint;
    stages: Array<StageResult>;
    status: JobStatus;
    owner: string;
    createdAt: Time;
    errorMessage?: string;
    expiryReason?: ExpiryReason;
    lastUpdated: Time;
    uploadedImage: ExternalBlob;
}
export type Time = bigint;
export type RetryJobResponse = {
    __kind__: "error";
    error: JobError;
} | {
    __kind__: "success";
    success: {
        jobId: bigint;
    };
};
export type JobError = {
    __kind__: "rateLimitExceeded";
    rateLimitExceeded: {
        message: string;
    };
} | {
    __kind__: "invalidState";
    invalidState: {
        message: string;
    };
} | {
    __kind__: "unauthorized";
    unauthorized: {
        message: string;
    };
} | {
    __kind__: "jobNotFound";
    jobNotFound: {
        message: string;
    };
};
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface StageResult {
    status: JobStatus;
    stageNumber: bigint;
    resultImage?: ExternalBlob;
    stageName: string;
}
export type JobResponse = {
    __kind__: "error";
    error: JobError;
} | {
    __kind__: "success";
    success: Job;
};
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type CreateJobResponse = {
    __kind__: "error";
    error: JobError;
} | {
    __kind__: "success";
    success: {
        jobId: bigint;
    };
};
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum ExpiryReason {
    timeout = "timeout"
}
export enum JobStatus {
    pending = "pending",
    completed = "completed",
    inProgress = "inProgress",
    failed = "failed"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    createJob(uploadedImage: ExternalBlob): Promise<CreateJobResponse>;
    getJob(jobId: bigint): Promise<Job | null>;
    getJobsByStatus(status: JobStatus, limit: bigint): Promise<Array<Job>>;
    getJobsSortedAsc(limit: bigint): Promise<Array<Job>>;
    getMyJobs(): Promise<Array<Job>>;
    processJob(jobId: bigint): Promise<JobResponse>;
    retryFailedJob(jobId: bigint): Promise<RetryJobResponse>;
}
import type { CreateJobResponse as _CreateJobResponse, ExpiryReason as _ExpiryReason, ExternalBlob as _ExternalBlob, Job as _Job, JobError as _JobError, JobResponse as _JobResponse, JobStatus as _JobStatus, RetryJobResponse as _RetryJobResponse, StageResult as _StageResult, Time as _Time, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async createJob(arg0: ExternalBlob): Promise<CreateJobResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.createJob(await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_CreateJobResponse_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJob(await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_CreateJobResponse_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJob(arg0: bigint): Promise<Job | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJob(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJob(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobsByStatus(arg0: JobStatus, arg1: bigint): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobsByStatus(to_candid_JobStatus_n27(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobsByStatus(to_candid_JobStatus_n27(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobsSortedAsc(arg0: bigint): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobsSortedAsc(arg0);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobsSortedAsc(arg0);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyJobs(): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyJobs();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyJobs();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async processJob(arg0: bigint): Promise<JobResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.processJob(arg0);
                return from_candid_JobResponse_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processJob(arg0);
            return from_candid_JobResponse_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async retryFailedJob(arg0: bigint): Promise<RetryJobResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.retryFailedJob(arg0);
                return from_candid_RetryJobResponse_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.retryFailedJob(arg0);
            return from_candid_RetryJobResponse_n32(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_CreateJobResponse_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CreateJobResponse): CreateJobResponse {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_ExpiryReason_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExpiryReason): ExpiryReason {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_JobError_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobError): JobError {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
async function from_candid_JobResponse_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobResponse): Promise<JobResponse> {
    return await from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_JobStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobStatus): JobStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
async function from_candid_Job_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Job): Promise<Job> {
    return await from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_RetryJobResponse_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RetryJobResponse): RetryJobResponse {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
async function from_candid_StageResult_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StageResult): Promise<StageResult> {
    return await from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Job]): Promise<Job | null> {
    return value.length === 0 ? null : await from_candid_Job_n14(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExpiryReason]): ExpiryReason | null {
    return value.length === 0 ? null : from_candid_ExpiryReason_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    stages: Array<_StageResult>;
    status: _JobStatus;
    owner: string;
    createdAt: _Time;
    errorMessage: [] | [string];
    expiryReason: [] | [_ExpiryReason];
    lastUpdated: _Time;
    uploadedImage: _ExternalBlob;
}): Promise<{
    id: bigint;
    stages: Array<StageResult>;
    status: JobStatus;
    owner: string;
    createdAt: Time;
    errorMessage?: string;
    expiryReason?: ExpiryReason;
    lastUpdated: Time;
    uploadedImage: ExternalBlob;
}> {
    return {
        id: value.id,
        stages: await from_candid_vec_n16(_uploadFile, _downloadFile, value.stages),
        status: from_candid_JobStatus_n19(_uploadFile, _downloadFile, value.status),
        owner: value.owner,
        createdAt: value.createdAt,
        errorMessage: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.errorMessage)),
        expiryReason: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.expiryReason)),
        lastUpdated: value.lastUpdated,
        uploadedImage: await from_candid_ExternalBlob_n22(_uploadFile, _downloadFile, value.uploadedImage)
    };
}
async function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _JobStatus;
    stageNumber: bigint;
    resultImage: [] | [_ExternalBlob];
    stageName: string;
}): Promise<{
    status: JobStatus;
    stageNumber: bigint;
    resultImage?: ExternalBlob;
    stageName: string;
}> {
    return {
        status: from_candid_JobStatus_n19(_uploadFile, _downloadFile, value.status),
        stageNumber: value.stageNumber,
        resultImage: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.resultImage)),
        stageName: value.stageName
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    error: _JobError;
} | {
    success: {
        jobId: bigint;
    };
}): {
    __kind__: "error";
    error: JobError;
} | {
    __kind__: "success";
    success: {
        jobId: bigint;
    };
} {
    return "error" in value ? {
        __kind__: "error",
        error: from_candid_JobError_n11(_uploadFile, _downloadFile, value.error)
    } : "success" in value ? {
        __kind__: "success",
        success: value.success
    } : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rateLimitExceeded: {
        message: string;
    };
} | {
    invalidState: {
        message: string;
    };
} | {
    unauthorized: {
        message: string;
    };
} | {
    jobNotFound: {
        message: string;
    };
}): {
    __kind__: "rateLimitExceeded";
    rateLimitExceeded: {
        message: string;
    };
} | {
    __kind__: "invalidState";
    invalidState: {
        message: string;
    };
} | {
    __kind__: "unauthorized";
    unauthorized: {
        message: string;
    };
} | {
    __kind__: "jobNotFound";
    jobNotFound: {
        message: string;
    };
} {
    return "rateLimitExceeded" in value ? {
        __kind__: "rateLimitExceeded",
        rateLimitExceeded: value.rateLimitExceeded
    } : "invalidState" in value ? {
        __kind__: "invalidState",
        invalidState: value.invalidState
    } : "unauthorized" in value ? {
        __kind__: "unauthorized",
        unauthorized: value.unauthorized
    } : "jobNotFound" in value ? {
        __kind__: "jobNotFound",
        jobNotFound: value.jobNotFound
    } : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
} | {
    failed: null;
}): JobStatus {
    return "pending" in value ? JobStatus.pending : "completed" in value ? JobStatus.completed : "inProgress" in value ? JobStatus.inProgress : "failed" in value ? JobStatus.failed : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    timeout: null;
}): ExpiryReason {
    return "timeout" in value ? ExpiryReason.timeout : value;
}
async function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    error: _JobError;
} | {
    success: _Job;
}): Promise<{
    __kind__: "error";
    error: JobError;
} | {
    __kind__: "success";
    success: Job;
}> {
    return "error" in value ? {
        __kind__: "error",
        error: from_candid_JobError_n11(_uploadFile, _downloadFile, value.error)
    } : "success" in value ? {
        __kind__: "success",
        success: await from_candid_Job_n14(_uploadFile, _downloadFile, value.success)
    } : value;
}
async function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StageResult>): Promise<Array<StageResult>> {
    return await Promise.all(value.map(async (x)=>await from_candid_StageResult_n17(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Job>): Promise<Array<Job>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Job_n14(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_JobStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobStatus): _JobStatus {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobStatus): {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
} | {
    failed: null;
} {
    return value == JobStatus.pending ? {
        pending: null
    } : value == JobStatus.completed ? {
        completed: null
    } : value == JobStatus.inProgress ? {
        inProgress: null
    } : value == JobStatus.failed ? {
        failed: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
