/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const JobError = IDL.Variant({
  'rateLimitExceeded' : IDL.Record({ 'message' : IDL.Text }),
  'invalidState' : IDL.Record({ 'message' : IDL.Text }),
  'unauthorized' : IDL.Record({ 'message' : IDL.Text }),
  'jobNotFound' : IDL.Record({ 'message' : IDL.Text }),
});
export const CreateJobResponse = IDL.Variant({
  'error' : JobError,
  'success' : IDL.Record({ 'jobId' : IDL.Nat }),
});
export const JobStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
  'failed' : IDL.Null,
});
export const StageResult = IDL.Record({
  'status' : JobStatus,
  'stageNumber' : IDL.Nat,
  'resultImage' : IDL.Opt(ExternalBlob),
  'stageName' : IDL.Text,
});
export const Time = IDL.Int;
export const ExpiryReason = IDL.Variant({ 'timeout' : IDL.Null });
export const Job = IDL.Record({
  'id' : IDL.Nat,
  'stages' : IDL.Vec(StageResult),
  'status' : JobStatus,
  'owner' : IDL.Text,
  'createdAt' : Time,
  'errorMessage' : IDL.Opt(IDL.Text),
  'expiryReason' : IDL.Opt(ExpiryReason),
  'lastUpdated' : Time,
  'uploadedImage' : ExternalBlob,
});
export const JobResponse = IDL.Variant({ 'error' : JobError, 'success' : Job });
export const RetryJobResponse = IDL.Variant({
  'error' : JobError,
  'success' : IDL.Record({ 'jobId' : IDL.Nat }),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'createJob' : IDL.Func([ExternalBlob], [CreateJobResponse], []),
  'getJob' : IDL.Func([IDL.Nat], [IDL.Opt(Job)], ['query']),
  'getJobsByStatus' : IDL.Func([JobStatus, IDL.Nat], [IDL.Vec(Job)], ['query']),
  'getJobsSortedAsc' : IDL.Func([IDL.Nat], [IDL.Vec(Job)], ['query']),
  'getMyJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'processJob' : IDL.Func([IDL.Nat], [JobResponse], []),
  'retryFailedJob' : IDL.Func([IDL.Nat], [RetryJobResponse], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const JobError = IDL.Variant({
    'rateLimitExceeded' : IDL.Record({ 'message' : IDL.Text }),
    'invalidState' : IDL.Record({ 'message' : IDL.Text }),
    'unauthorized' : IDL.Record({ 'message' : IDL.Text }),
    'jobNotFound' : IDL.Record({ 'message' : IDL.Text }),
  });
  const CreateJobResponse = IDL.Variant({
    'error' : JobError,
    'success' : IDL.Record({ 'jobId' : IDL.Nat }),
  });
  const JobStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
    'failed' : IDL.Null,
  });
  const StageResult = IDL.Record({
    'status' : JobStatus,
    'stageNumber' : IDL.Nat,
    'resultImage' : IDL.Opt(ExternalBlob),
    'stageName' : IDL.Text,
  });
  const Time = IDL.Int;
  const ExpiryReason = IDL.Variant({ 'timeout' : IDL.Null });
  const Job = IDL.Record({
    'id' : IDL.Nat,
    'stages' : IDL.Vec(StageResult),
    'status' : JobStatus,
    'owner' : IDL.Text,
    'createdAt' : Time,
    'errorMessage' : IDL.Opt(IDL.Text),
    'expiryReason' : IDL.Opt(ExpiryReason),
    'lastUpdated' : Time,
    'uploadedImage' : ExternalBlob,
  });
  const JobResponse = IDL.Variant({ 'error' : JobError, 'success' : Job });
  const RetryJobResponse = IDL.Variant({
    'error' : JobError,
    'success' : IDL.Record({ 'jobId' : IDL.Nat }),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'createJob' : IDL.Func([ExternalBlob], [CreateJobResponse], []),
    'getJob' : IDL.Func([IDL.Nat], [IDL.Opt(Job)], ['query']),
    'getJobsByStatus' : IDL.Func(
        [JobStatus, IDL.Nat],
        [IDL.Vec(Job)],
        ['query'],
      ),
    'getJobsSortedAsc' : IDL.Func([IDL.Nat], [IDL.Vec(Job)], ['query']),
    'getMyJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'processJob' : IDL.Func([IDL.Nat], [JobResponse], []),
    'retryFailedJob' : IDL.Func([IDL.Nat], [RetryJobResponse], []),
  });
};

export const init = ({ IDL }) => { return []; };