/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CreateJobResponse = { 'error' : JobError } |
  { 'success' : { 'jobId' : bigint } };
export type ExpiryReason = { 'timeout' : null };
export type ExternalBlob = Uint8Array;
export interface Job {
  'id' : bigint,
  'stages' : Array<StageResult>,
  'status' : JobStatus,
  'owner' : string,
  'createdAt' : Time,
  'errorMessage' : [] | [string],
  'expiryReason' : [] | [ExpiryReason],
  'lastUpdated' : Time,
  'uploadedImage' : ExternalBlob,
}
export type JobError = { 'rateLimitExceeded' : { 'message' : string } } |
  { 'invalidState' : { 'message' : string } } |
  { 'unauthorized' : { 'message' : string } } |
  { 'jobNotFound' : { 'message' : string } };
export type JobResponse = { 'error' : JobError } |
  { 'success' : Job };
export type JobStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null } |
  { 'failed' : null };
export type RetryJobResponse = { 'error' : JobError } |
  { 'success' : { 'jobId' : bigint } };
export interface StageResult {
  'status' : JobStatus,
  'stageNumber' : bigint,
  'resultImage' : [] | [ExternalBlob],
  'stageName' : string,
}
export type Time = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'cancelJob' : ActorMethod<[bigint], undefined>,
  'createJob' : ActorMethod<[ExternalBlob], CreateJobResponse>,
  'getJob' : ActorMethod<[bigint], [] | [Job]>,
  'getJobsByStatus' : ActorMethod<[JobStatus, bigint], Array<Job>>,
  'getJobsSortedAsc' : ActorMethod<[bigint], Array<Job>>,
  'getMyJobs' : ActorMethod<[], Array<Job>>,
  'processJob' : ActorMethod<[bigint], JobResponse>,
  'retryFailedJob' : ActorMethod<[bigint], RetryJobResponse>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];